## Pre-processing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [2]:
transaction_data_path = '/Users/harsh/Desktop/Intelligent Reasoning Systems/Project/Raw Data/DATA_Cleaned.csv'

data = pd.read_csv(transaction_data_path, encoding='ISO-8859-1')
data.columns = data.columns.str.replace(' ', '_').str.upper()
data.head()

/var/folders/4c/99wh1f85111309s8ydsfjmlr0000gn/T/ipykernel_64482/3099024647.py:3: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(transaction_data_path, encoding='ISO-8859-1')

,#,DOCCUR,SUPPLIER_NAME,SUPPLIER_CODE,DOC_DATE,DELIVERY_DATE,EXPECTED_DATE,FOLLOW_UP_DATE,PO_VALUE,ITEM_CODE,ITEM_NAME,FG_ITEM_DESCRIPTION,ITEM_DETAILS,MANUFACTURER_PART_NO,HSN,UOM,ORDERED_QUANTITY,PRICE,ITEM_VALUE
0,26968,INR,24 STEEL IMPRESSIONS PRIVATE LIMITED,VD004075,06-06-2023,28-10-2023,NaN,NaN,"2,07,680.00",MC11560,Bracket no A-081-G MDR Locking Strip,Conveyor,Bracket no A-081-G MDR Locking Strip,NaN,8431.39.90,Nos,"2,000.00",88,"1,76,000.00"
1,42455,INR,24 STEEL IMPRESSIONS PRIVATE LIMITED,VD004075,02-01-2024,30-01-2024,NaN,NaN,"2,07,680.00",4556800,Locking Plate,Conveyor,Bracket no A-081-G MDR Locking Strip,NaN,8431.39.90,NOS,"2,000.00",88,"1,76,000.00"
2,45582,INR,24 STEEL IMPRESSIONS PRIVATE LIMITED,VD004075,24-02-2024,29-02-2024,NaN,NaN,"11,800.00",NaN,Charges for embossing tool trial Proto,Embossing tool trial,NaN,NaN,NaN,NaN,0,"10,000.00","10,000.00"
3,9868,INR,3ACES TECHNOLOGIES,VD003840,29-11-2022,07-12-2022,NaN,NaN,"23,60,431.88",NaN,DR Solution @12,NaN,NaN,NaN,NaN,NaN,0,"16,72,800.00","16,72,800.00"
4,9869,INR,3ACES TECHNOLOGIES,VD003840,29-11-2022,07-12-2022,NaN,NaN,"23,60,431.88",NaN,During The DR Drill Acrivity @2,NaN,NaN,NaN,NaN,NaN,0,"1,27,566.00","1,27,566.00"

In [3]:
data = data.drop(labels=['#', 'DOCCUR', 'SUPPLIER_NAME', 'EXPECTED_DATE', 'FOLLOW_UP_DATE'], axis=1)

In [4]:
data.head(10)

,SUPPLIER_CODE,DOC_DATE,DELIVERY_DATE,PO_VALUE,ITEM_CODE,ITEM_NAME,FG_ITEM_DESCRIPTION,ITEM_DETAILS,MANUFACTURER_PART_NO,HSN,UOM,ORDERED_QUANTITY,PRICE,ITEM_VALUE
0,VD004075,06-06-2023,28-10-2023,"2,07,680.00",MC11560,Bracket no A-081-G MDR Locking Strip,Conveyor,Bracket no A-081-G MDR Locking Strip,NaN,8431.39.90,Nos,"2,000.00",88,"1,76,000.00"
1,VD004075,02-01-2024,30-01-2024,"2,07,680.00",4556800,Locking Plate,Conveyor,Bracket no A-081-G MDR Locking Strip,NaN,8431.39.90,NOS,"2,000.00",88,"1,76,000.00"
2,VD004075,24-02-2024,29-02-2024,"11,800.00",NaN,Charges for embossing tool trial Proto,Embossing tool trial,NaN,NaN,NaN,NaN,0,"10,000.00","10,000.00"
3,VD003840,29-11-2022,07-12-2022,"23,60,431.88",NaN,DR Solution @12,NaN,NaN,NaN,NaN,NaN,0,"16,72,800.00","16,72,800.00"
4,VD003840,29-11-2022,07-12-2022,"23,60,431.88",NaN,During The DR Drill Acrivity @2,NaN,NaN,NaN,NaN,NaN,0,"1,27,566.00","1,27,566.00"
5,VD003840,29-11-2022,07-12-2022,"23,60,431.88",NaN,"VM Installation & Configuration, Virtual Dedic...",NaN,NaN,NaN,NaN,NaN,0,"2,00,000.00","2,00,000.00"
6,VD003840,20-03-2024,21-03-2024,"1,64,492.00",NaN,DR Solution @1,DR Solution @1,NaN,NaN,NaN,NaN,0,"1,39,400.00","1,39,400.00"
7,VD001234,17-08-2021,17-08-2021,"9,14,500.00",NaN,PRODUCT IMPLEMENTATION & SERVICES FOR SEIMENS ...,NaN,NaN,NaN,NaN,NaN,0,"6,25,000.00","6,25,000.00"
8,VD001234,17-08-2021,17-08-2021,"9,14,500.00",NaN,ePlan TC side setup on Test server,NaN,NaN,NaN,NaN,NaN,0,"1,50,000.00","1,50,000.00"
9,VD001234,25-01-2023,10-02-2023,"8,64,940.00",NaN,NX CAD/CAM Total Machining NX 12490 for one y...,NX CAD/CAM Total Machining NX 12490 for one y...,NaN,NaN,NaN,NaN,0,"7,08,000.00","7,08,000.00"

In [5]:
data[['SUPPLIER_CODE', 'DOC_DATE', 'DELIVERY_DATE', 'ITEM_CODE', 'ITEM_NAME', 'FG_ITEM_DESCRIPTION', 'ITEM_DETAILS', 'MANUFACTURER_PART_NO', 'HSN', 'UOM']].nunique()

SUPPLIER_CODE            1642
DOC_DATE                  744
DELIVERY_DATE             968
ITEM_CODE               20592
ITEM_NAME               23937
FG_ITEM_DESCRIPTION      6666
ITEM_DETAILS            11598
MANUFACTURER_PART_NO     9335
HSN                      1670
UOM                        78
dtype: int64

In [6]:
string_fields = ['SUPPLIER_CODE', 'ITEM_CODE', 'MANUFACTURER_PART_NO', 'HSN', 'UOM']

numerical_fields = ['PO_VALUE', 'ORDERED_QUANTITY', 'PRICE', 'ITEM_VALUE']

In [7]:
# convert the string fields from object to string
for field in string_fields:
    data[field] = data[field].astype('str')
    print(field)
    print(data[field].dropna().unique())
    print()

SUPPLIER_CODE
['VD004075' 'VD003840' 'VD001234' ... 'VD002726' 'VD004346' 'VD003989']

ITEM_CODE
['MC11560' '4556800' 'nan' ... '4248101' '3734701' '3079000']

MANUFACTURER_PART_NO
['nan' '3205 A- 2RS1' 'FYTB 17 TF' ... 'ps4 wwe 2k20' 'ZSPL-ADT-PTLLK001'
 'ZSPL-ADT-CCLK001']

HSN
['8431.39.90' 'nan' '8523.80.20' ... '7323.94.20' '9100.02.38'
 '8536.69.00']

UOM
['Nos' 'NOS' 'nan' 'number' 'nos' 'mtr' 'Mtr' 'Set' 'meter' 'kgs' 'Kg'
 'Nos.' 'Pack' 'Pkt' 'KG' 'kg' 'SET' 'NOS.' 'Ft' 'Number' 'Kg.' 'SQFT' 'M'
 'LS' 'Ltr' 'KGS' 'MTR' 'ROLL' 'pkt' 'NUMBER' 'NOs' 'NO' 'BOX' 'MTRS'
 'set' 'Mtrs' 'Pcs' 'PKT(500)' 'PKT' 'piece' 'sets' 'Numbers' 'Sq ft' 'No'
 'MT' 'nos.' 'Pcs.' 'Square Feet' 'PCS.' 'kG' 'Kgs' 'Mtr.' 'Sqft' 'EA'
 'roll' 'Pair' 'Box' 'Roll' 'Square Inches' 'no' 'NoS' 'QTY' 'No.' 'rolls'
 'PCS' 'Packs' 'Can' 'Each' 'PKT.' 'Pkt.' 'Liters' 'pcs' 'Sq Inch' 'UOM'
 'mm' 'Sqft.' 'unit' 'mtr.' 'METER']

In [8]:
# convert the numerical fields from object to float
for field in numerical_fields:
    data[field] = data[field].str.replace(',', '').astype('float64')

In [9]:
data.dtypes

SUPPLIER_CODE            object
DOC_DATE                 object
DELIVERY_DATE            object
PO_VALUE                float64
ITEM_CODE                object
ITEM_NAME                object
FG_ITEM_DESCRIPTION      object
ITEM_DETAILS             object
MANUFACTURER_PART_NO     object
HSN                      object
UOM                      object
ORDERED_QUANTITY        float64
PRICE                   float64
ITEM_VALUE              float64
dtype: object

In [10]:
# data.describe(include=np.number)

np.round(data.describe(include=np.number).transpose(), decimals=2)

,count,mean,std,min,25%,50%,75%,max
PO_VALUE,50461.0,1732695.17,12647798.49,0.0,46350.40,161936.71,500471.09,4.071000e+08
ORDERED_QUANTITY,50461.0,1125.47,118219.64,0.0,2.00,10.00,70.00,2.649396e+07
PRICE,50461.0,62520.85,1003461.33,0.0,64.66,676.00,6228.00,7.404293e+07
ITEM_VALUE,50461.0,180632.95,2215779.06,0.0,1867.00,9800.00,49500.00,3.450000e+08

In [11]:
X_numerical = data[numerical_fields]
X_numerical.corr()

                  PO_VALUE  ORDERED_QUANTITY     PRICE  ITEM_VALUE
PO_VALUE          1.000000          0.011481  0.165060    0.334048
ORDERED_QUANTITY  0.011481          1.000000 -0.000592    0.054125
PRICE             0.165060         -0.000592  1.000000    0.447551
ITEM_VALUE        0.334048          0.054125  0.447551    1.000000

In [12]:
Y = data['SUPPLIER_CODE']

In [13]:
from sklearn.feature_selection import mutual_info_classif

mi_scores = mutual_info_classif(X_numerical, Y)
mi_scores = pd.Series(mi_scores, name="MI Scores", index=numerical_fields)
mi_scores = mi_scores.sort_values(ascending=False)
mi_scores

/Users/harsh/miniconda3/lib/python3.12/site-packages/threadpoolctl.py:1214: RuntimeWarning:
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

PO_VALUE            3.441697
PRICE               2.069668
ITEM_VALUE          0.851808
ORDERED_QUANTITY    0.841774
Name: MI Scores, dtype: float64